# main settings
title:            Selections from John James Audubon's Birds of America at the Lilly Library
description:      Online exhibit of the Lilly Librarys 1st edition of John James Audubon''s Birds of America.  This site was created using wax/minimal exhibitions
url:              'https://ericayhayes.github.io'
baseurl:          '/audubon'

# build settings
permalink:        pretty
exclude:          [Gemfile*, Rakefile, node_modules, vendor, spec, README.md, wax_tasks]

# wax collection settings
collections:
  audubon:
    output: true
    layout: iiif-item-page
    metadata:
      source: audubon.csv
    images:
      source: iiif/audubon
      iiif:
        label: title

# wax search index settings
lunr_index:
  - file: 'js/lunr-index.json'
    collections:
      audubon:
        content: false
        fields:
          - artist
          - title
          - source
          - volume
          - plate
          - repository
          - current_location
          - category
          - current_population


# menu settings
menu:
  - label: About
    sub:
    - label: About John James Audubon
      link: /about/
    - label: Credits
      link: /credits/
  - label: Gallery
    link: /gallery/
  - label: Browse
    link: /exhibits/


# search tests
quoll:
  main:
    page: '/'
    terms:
      - bird
      - map
      - manuscript

# javascript dependencies
js:
  jquery:
    version: 3.2.1
    cdn: //code.jquery.com/jquery-3.2.1.min.js
  popper:
    version: 1.12.9
    cdn: //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  bootstrap:
    version: 4.0.0
    cdn: //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  leaflet:
    version: 1.3.1
    cdn: //unpkg.com/leaflet@1.3.1/dist/leaflet.js
  leaflet-iiif:
    version: 2.0.1
    cdn: //cdn.jsdelivr.net/npm/leaflet-iiif@2.0.1/leaflet-iiif.min.js

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
